/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as StudioRouteImport } from './app/studio'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as HistoryRouteImport } from './app/history'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as ContactsRouteImport } from './app/contacts'
import { Route as IndexRouteImport } from './app/index'
import { Route as StreamsIndexRouteImport } from './app/streams/index'
import { Route as StreamsStreamIdRouteImport } from './app/streams/$streamId'
import { Route as ClaimPageIdRouteImport } from './app/claim/$pageId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsStreamIdRoute = StreamsStreamIdRouteImport.update({
  id: '/streams/$streamId',
  path: '/streams/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimPageIdRoute = ClaimPageIdRouteImport.update({
  id: '/claim/$pageId',
  path: '/claim/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/claim/$pageId': typeof ClaimPageIdRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/claim/$pageId': typeof ClaimPageIdRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/streams': typeof StreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/claim/$pageId': typeof ClaimPageIdRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/studio'
    | '/claim/$pageId'
    | '/streams/$streamId'
    | '/streams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/studio'
    | '/claim/$pageId'
    | '/streams/$streamId'
    | '/streams'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/studio'
    | '/claim/$pageId'
    | '/streams/$streamId'
    | '/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  ClaimPageIdRoute: typeof ClaimPageIdRoute
  StreamsStreamIdRoute: typeof StreamsStreamIdRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/$streamId': {
      id: '/streams/$streamId'
      path: '/streams/$streamId'
      fullPath: '/streams/$streamId'
      preLoaderRoute: typeof StreamsStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$pageId': {
      id: '/claim/$pageId'
      path: '/claim/$pageId'
      fullPath: '/claim/$pageId'
      preLoaderRoute: typeof ClaimPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  ClaimPageIdRoute: ClaimPageIdRoute,
  StreamsStreamIdRoute: StreamsStreamIdRoute,
  StreamsIndexRoute: StreamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
